package emotionalsongs;

import java.util.ListResourceBundle;

/*
 * Progetto svolto da:
 * 
 * Della Chiesa Mattia 749904, Ateneo di Varese
 * 
 */

 /**
  * Classe che contiene le traduzioni delle parole chiave in lingua Italiana
  */
public class Language extends ListResourceBundle{

    /**
     * Returns an array in which each item is a pair of objects in an
     * {@code Object} array. The first element of each pair is
     * the key, which must be a {@code String}, and the second
     * element is the value associated with that key.  See the class
     * description for details.
     *
     * @return an array of an {@code Object} array representing a
     * key-value pair.
     */
    @Override
    protected Object[][] getContents() {

        return new Object[][] {
            {"Address"," Indirizzo:"},
            {"CancelPlaylistWithSongs"," All'interno della playlist ci sono %s canzoni:\n"},
            {"CancelEmotionRegistrationPrompt"," Interrompere la registrazione delle emozioni? I dati non salvati verranno persi. s/n" },
            {"CF"," Codice fiscale:"},
            {"Choice"," \n "+TextUtils.WHITE+"Scelta: "+TextUtils.RESET},
            {"ChosenEmotion"," Emozione scelta:\n\n\t"},
            {"ChosenSongIsAlreadyInPlaylist"," La canzone scelta e' gia' presente all'interno della playlist. "},
            {"CommentsLeftByUser"," Commenti lasciati da "},
            {"CompleteFeedbackPrompt"," Desideri completare il procedimento di inserimento emozioni per questa playlist? s/n"},
            {"Confirm"," \n Conferma? (s/n): "},
            {"ConfirmData"," Confermare i dati inseriti:"},
            {"ContinueAddingSongsPrompt","\n Continuare con l'inserimento di brani musicali? s/n"},
            {"CreatePlaylist","Crea Playlist"},
            {"CreatePlaylistSubtitle"," CREAZIONE PLAYLIST"},
            {"DEBUG_BeginEmotionRepositoryInitialization","Inizializzazione repository emozioni in corso..."},
            {"DEBUG_BeginSongRepositoryInitialization","Inizializzazione repository canzoni in corso..."},
            {"DEBUG_CFContainsInvalidCharacters","Il codice fiscale contiene caratteri non ammessi."},
            {"DEBUG_CFHasFailedChecksum","Il codice fiscale ha fallito il checksum."},
            {"DEBUG_CFIsValid","Il codice fiscale e' valido."},
            {"DEBUG_ClearScreen","In questo punto avviene un cls()"},
            {"DEBUG_CommaFound","Rilevato valore contenente una virgola."},
            {"DEBUG_CurrentlyUsedMemory", "Memoria attualmente utilizzata: "},
            {"DEBUG_DebugModeDisabled","La modalita' di debug e' stata disattivata.\n"},
            {"DEBUG_DebugModeEnabled","La modalita' di debug e' stata attivata.\n"},
            {"DEBUG_EmotionsInRepository","La repository delle emozioni contiene %s entry."},
            {"DEBUG_ExceptionWhileClosingCMD", "Eccezione rilevata mentre si tentava di chiudere il prompt dei comandi."},
            {"DEBUG_FileNotFound","Il file %s non e' stato trovato, ne e' stato creato uno nuovo."},
            {"DEBUG_NumberOfResultsFound","Sono stati trovati %s risultati"},
            {"DEBUG_NumberOfResultsKept","Di questi risultati ne sono stati mantenuti i primi %s"},
            {"DEBUG_PlaylistBuildSuccess","Playlist costruita correttamente!"},
            {"DEBUG_ProcessDuration","Tempo impiegato: "},
            {"DEBUG_RepositoryDoesNotContainsElement"," La repos"},
            {"DEBUG_RepositoryBuildSuccess","Repository costruita correttamente!"},
            {"DEBUG_ResultsObtained","Risultati ottenuti: "},
            {"DEBUG_Score","Punteggio: "},
            {"DEBUG_SearchByTitleCompleted", "Ricerca per titolo completata!\n\t Sono stati trovati %s risultati."},
            {"DEBUG_SongTitleBeingSearched","Sto ricercando la canzone: "},
            {"DEBUG_SongsInRepository","La repository delle canzoni contiene %s entry."},
            {"DEBUG_UserAlreadyProvidedFeedback","L'utente %s ha gia' fornito un feedback sull'elemento [%s] le emozioni provate sono state sovrascritte!"},
            {"DEBUG_UserCSV","User's CSV: "},
            {"Email"," Email:"},
            {"EmotionsListColored",TextUtils.GREEN+"Amazement"+TextUtils.RESET+"," +TextUtils.CYAN+" Solemnity"+TextUtils.RESET+"," +TextUtils.PURPLE+" Tenderness"+TextUtils.RESET+"," +TextUtils.BLUE+" Nostalgia"+TextUtils.RESET+"," +TextUtils.CYAN+" Calmness"+TextUtils.RESET+"," +TextUtils.RED+" Power"+TextUtils.RESET+"," +TextUtils.YELLOW+" Joy"+TextUtils.RESET+"," +TextUtils.RED+" Tension"+TextUtils.RESET+"," +TextUtils.BLUE+" Sadness"+TextUtils.RESET+"."},
            {"EmotionsFeltForSong"," Emozioni provate per la canzone:\n\n \t\t"},
            {"EmotionsSelection", "\n Per interrompere l'inserimento utilizzare il comando '"+TextUtils.RED+"cancel"+TextUtils.RESET+"', oppure '"+TextUtils.GREEN +"save" +TextUtils.RESET+"' per salvare il tuo feedback.\n I dati inseriti potranno essere modificati piu' volte prima di effettuare il salvataggio. "},
            {"ERROR_CannotRetrieveElementFromRepository", "Impossibile recuperare l'elemento."},
            {"ERROR_CFAlreadyInUse","Esiste gia' un utente con quel codice fiscale, effettuare il login. "},
            {"ERROR_CFMustBe16CharLong","Il codice fiscale dev'essere lungo 16 caratteri. "},
            {"ERROR_FileNotFoundExceptionOnSaveFeedback","E' stato rilevato un errore in fase di salvataggio, si prega di contattare il supporto tecnico.\n Errore: FileNotFoundException on saveFeedback"},
            {"ERROR_GenericIOError","E' stato rilevato un errore, si prega di contattare il support tecnico.\n Errore: IOException "},
            {"ERROR_InvalidAddress","Indirizzo non valido. Sono stati forniti %s valori, mentre sono richiesti %s."},
            {"ERROR_InvalidAddressPrompt","Indirizzo non valido. Inserire nuovamente: "},
            {"ERROR_InvalidCF","Il valore inserito non rappresenta un codice fiscale regolare. "},
            {"ERROR_InvalidEmailAddressPrompt","L'indirizzo email inserito non e' valido\n Inserire nuovamente: "},
            {"ERROR_InvalidInput"," Il valore inserito non e' valido. "},
            {"ERROR_InvalidInputFormat","E' stato inserito un valore che non rispecchia le specifiche richieste."},
            {"ERROR_InvalidInputPrompt","Il valore inserito non e' valido. Inserire nuovamente: "},
            {"ERROR_InvalidIntegerInputPrompt","Il valore inserito non e' un numero intero. Inserire nuovamente: "},
            {"ERROR_InvalidSongUUID","UUID non presente nella repository delle canzoni."},
            {"ERROR_IOExceptionBuildPlaylist","E' stato rilevato un errore in fase di realizzazione del repository emozioni, si prega di contattare il supporto tecnico.\n Errore: IOException on BuildPlaylist "},
            {"ERROR_IOExceptionBuildEmotionRepo","E' stato rilevato un errore in fase di avvio, si prega di contattare il support tecnico.\n Errore: IOException while building the emotions repository "},
            {"ERROR_IOExceptionOnSaveFeedback","E' stato rilevato un errore in fase di salvataggio, si prega di contattare il supporto tecnico.\n Errore: IOException on saveFeedback "},
            {"ERROR_LanguageNotSupported","Il linguaggio inserito non e' supportato oppure non e' stato riconosciuto"},
            {"ERROR_LoginFailed","E' stato rilevato un errore durante la fase di login, si prega di contattare il supporto utenti.\n \t Errore rilevato: AddressNotValid on login\n"},
            {"ERROR_NoFeedbackPresent" , "E' necessario inserire almeno una valutazione prima di salvare il proprio feedback"},
            {"ERROR_NoMoreComments","Non ci sono altri commenti. "},
            {"ERROR_NoPlaylistsPresent"," Non sono presenti playlist nell'archivio. Prima di utilizzare questa funzionalità e' necessario creare una playlist."},
            {"ERROR_NoPreviousPages","Non ci sono pagine precedenti. "},
            {"ERROR_NoNextPages","Non ci sono altre pagine. "},
            {"ERROR_NotAllFieldCompiled","Non tutti i campi sono stati compilati"},
            {"ERROR_PasswordIsEmpty","E' stata immessa una password vuota."},
            {"ERROR_Tag","ERRORE"},
            {"ERROR_UnrecognizedCommand","Il comando inserito non e' stato riconosciuto. "},
            {"ERROR_UnrecognizedCommandPrompt","Il comando inserito non e' stato riconosciuto. Inserire nuovamente: "},
            {"ERROR_UserArchiveNotFound","Impossibile effettuare il login, non e' stato trovato l'archivio utenti."},
            {"ERROR_UsernameAlreadyExistsPrompt","L'username inserito esiste gia'. Inserire nuovamente: "},
            {"ERROR_ValueIsNullOrInvalidPrompt","E' stato inserito un valore nullo o non valido, inserire nuovamente: "},
            {"ERROR_ValueMustBeInsideInterval","Il valore deve essere compreso tra %s e %s."},
            {"ERROR_ValueMustBeInsideIntervalPrompt","Il valore deve essere compreso tra %s e %s. Inserire nuovamente: "},
            {"FeedbackRegistered",TextUtils.GREEN+" Feedback registrato" + TextUtils.RESET +"!"},
            {"IncorrectLogin"," Username o password errati!"},
            {"GoodbyeMessage"," Grazie per aver utilizzato la nostra piattaforma!"},
            {"InsertAddressInFormat"," Inserisci il tuo indirizzo nel formato:\n \t<Nome della Via/piazza>, <numero civico>, <cap>, <citta'>, <provincia>\n Indirizzo: "},
            {"InsertAuthorName"," Inserisci il nome dell'autore: "},
            {"InsertCF"," Inserisci il tuo codice fiscale: "},
            {"InsertComment", " Dicci perche' la canzone "+TextUtils.YELLOW+"\"%s\""+TextUtils.RESET+" ti fa provare %s:"+TextUtils.RESET+"\n"},
            {"InsertCommentPrompt", " Desideri aggiungere un commento alla valutazione associata a quest'emozione? s/n"},
            {"InsertEmail"," Inserisci il tuo indirizzo email: "},
            {"InsertNameSurname"," Inserisci il tuo nome e cognome separati da uno spazio: "},
            {"InsertPlaylistName"," Inserire il nome della playlist: "},
            {"InsertPlaylistEmotionsPrompt", "\n Si desidera registrare delle emozioni associate a dei brani all'interno della playlist? s/n"},
            {"InsertPassword"," Inserire password: "},
            {"InsertSongTitle"," Inserisci il titolo della canzone: "},
            {"InsertUsername"," Inserire nome utente: "},
            {"InsertYearOfRelease"," Inserisci l'anno di pubblicazione: "},
            {"LanguageOptionsSubtitle"," OPZIONI LINGUAGGIO"},
            {"ListCommandsViewSongEmotion"," \n Se desideri visualizzare i commenti lasciati dagli altri utenti su questa canzone inserisci\n il comando '"+TextUtils.YELLOW+"show comments"+TextUtils.RESET+"'. Se invece desideri registrare le emozioni provate durante l'ascolto di \n questo brano inserisci il comando '"+TextUtils.GREEN+"register emotions"+TextUtils.RESET+"' altrimenti inserisci '"+TextUtils.RED+"cancel"+TextUtils.RESET+"' per tornare indietro."},
            {"ListOfSongsInPlaylist"," Elenco brani presenti nella playlist '"+TextUtils.YELLOW+"%s"+TextUtils.RESET+"':\n "},
            {"LoginRequired"," Per utilizzare questa funzionalita' e' necessario effettuare prima il login."},
            {"MenuSelection"," Inserire un "+TextUtils.YELLOW+"numero"+TextUtils.RESET+" per selezionare l'opzione desiderata; inserire il comando '"+TextUtils.GREEN+"change language"+TextUtils.RESET+"' per\n modificare il linguaggio dell'applicazione, oppure '"+TextUtils.RED+"exit"+TextUtils.RESET+"' per uscire."},
            {"MenuSubtitle"," MENU PRINCIPALE"},
            {"MenuOption1"," Informazioni"},
            {"MenuOption2"," Consulta repository canzoni"},
            {"MenuOption3"," Login"},
            {"MenuOption3_1"," Log out"},
            {"MenuOption4"," Registrati all'applicazione"},
            {"MenuOption5"," Le mie playlist"},
            {"MyPlaylistSubtitle"," LE MIE PLAYLIST"},
            {"Name"," Nominativo:"},
            {"NavigateResults"," \n Inserire i comandi '"+TextUtils.GREEN+"next"+TextUtils.RESET+"' e '"+TextUtils.CYAN+"previous"+TextUtils.RESET+"' per navigare tra i risultati oppure '"+TextUtils.RED+"cancel"+TextUtils.RESET+"' per tornare indietro."},
            {"NoPlaylistPresentInArchive"," \t Non sono presenti playlist nell'archvio."},
            {"NoSongCommentsFound"," Ci dispiace, nessuno ha lasciato dei commenti per questa canzone."},
            {"NoSearchResultsYielded"," Non sono state trovate canzoni all'interno della repository.\n Vuoi effettuare un'altra ricerca? s/n"},
            {"NoSearchResultsYieldedForKeywords"," Non sono state trovate canzoni all'interno della repository oppure sono stati restituiti troppi risultati (utilizzare un cirterio piu' ristretto).\n Vuoi effettuare un'altra ricerca? s/n"},
            {"NoEmotionsRegisteredForSong"," Non sono presenti emozioni registrate per la canzone:"},
            {"NoEmotionsRegisteredForSongPromptUser"," Non sono ancora state inserite emozioni per questa canzone, desiderli farlo adesso? s/n"},
            {"OptionSelection"," Inserire un "+TextUtils.YELLOW+"numero"+TextUtils.RESET+" per selezionare l'opzione desiderata oppure '"+TextUtils.RED+"cancel"+TextUtils.RESET+"' per tornare indietro."},
            {"PageCounter"," [Pagina %s di %s]"},
            {"Password"," Password:"},
            {"PlaylistCreationAborted"," Creazione playlist annullata! "},
            {"PlaylistHasBeenCreated"," La playlist e' stata creata!"},
            {"PlaylistSelection"," Inserisci un "+TextUtils.YELLOW + "numero" + TextUtils.RESET +" per selezionare la playlist, '"+TextUtils.GREEN+"next"+TextUtils.RESET+"' o '"+TextUtils.CYAN+"previous"+TextUtils.RESET+"' per \n navigare tra le pagine dei risultati oppure '"+TextUtils.RED+"cancel"+TextUtils.RESET+"' per tornare indietro."},
            {"PlaylistSuccessfullySaved"," La playlist e' stata salvata correttamente! "},
            {"PressEnterToContinue"," Premere invio per continuare..."},
            {"ProjectInfoSubtitle", "IL PROGETTO"},
            {"ProjectInfo1"," Dalle danze greche agli inni e antifone del medioevo; dall'ars nova del 1300 alla stagione romantica dell'illuminismo. Nel corso dei vari millenni, l'essere umano ha sviluppato un'immenso fascino nei confronti della musica a tal punto che, nel Romanticismo, essa divento' un linguaggio puro e assoluto l'unico in grado di esprimere concetti universali e di attingere direttamente all'\"ineffabile\" e all' \"infinito\".\n Uno dei principali motivi legati a questo fascino universale risiede nell'immenso patrimonio emotivo che la musica offre a tutti i suoi ascoltatori. Lo scopo di questa piattaforma consiste nel raccogliere e catalogare le sensazioni emotive provate dai nostri utenti durante l'ascolto di brani musicali tramite il modello definito dalla Geneva Emotional Music Scale (GEMS), una scala fattoriale che suddivide le emozioni provate dall'utente in nove categorie di emozioni:"},
            {"ProjectInfo2"," Tramite la nostra piattaforma i nostri utenti saranno in grado di creare una propria playlist e di popolarla con uno o più canzoni presenti all'interno di una vasta repository contenente piu' di 380'000 brani musicali. Ognuno di questi brani potra' essere annotato con i tag emozionali provati durante l'ascolto e, per ciascuna di queste emozioni, sara' possibile includere un commento pubblico, che offrira' agli altri utenti della piattaforma l'opportunità di avere uno sguardo sulle introspettive altrui e su come queste possano essere influenzate dal proprio passato."},
            {"PromptUserToModifyComment","\n\n Desideri modificarlo? s/n"},
            {"PromptUserToRegisterAccount"," Se desideri essere il primo a registrare delle emozioni per questa canzone, effettua\n il login o registrati alla piattaforma!"},
            {"PromptUserToRegisterEmotions"," Desideri registrare le emozioni che hai provato nell'ascolto di questo brano? s/n"},
            {"PromptPreserveProgressInPlaylistCreation"," Desideri mantenerle e procedere alla creazione della playlist? s/n"},
            {"PromptReturn"," Desideri tornare indietro? s/n"},
            {"RateEmotion","\n Su una scala da 1 ("+TextUtils.RED+"per niente"+TextUtils.RESET+") a 5 ("+TextUtils.GREEN+"molto"+TextUtils.RESET+"), quanto e' stata provata quest'emozione nell'ascolto del brano?"},
            {"RegisterEmotionSubtitle"," REGISTRA EMOZIONE"},
            {"RegisteringEmotionsForSong"," E' in corso la registrazione delle emozioni provate per la canzone: "+ TextUtils.YELLOW + "%s"+ TextUtils.RESET +"\n Selezionare l'emozione provata durante l'ascolto del brano:\n\t"},
            {"RegistrationCancelled"," \n Registrazione annullata\n"},
            {"RegistrationNecessary"," \n\n Prima di utilizzare questa funzionalita' e' necessario creare una nuova playlist."},
            {"RegistrationSubtitle", "REGISTRAZIONE"},
            {"RegistrationSucceeded"," \n Registrazione avvenuta con successo\n "},
            {"RequestConfirmation"," Confermare? s/n"},
            {"SearchSelectionMethod"," %1$s["+TextUtils.BLUE+"1"+TextUtils.RESET+"] Ricerca per titolo\n %1$s["+TextUtils.BLUE+"2"+TextUtils.RESET+"] Ricerca per autore e anno\n\n Inserisci un "+TextUtils.YELLOW+"numero"+TextUtils.RESET+" per selezionare il metodo di ricerca oppure inserisci '"+TextUtils.RED+"cancel"+TextUtils.RESET+"' per tornare indietro."},
            {"SearchSongSubtitle"," RICERCA CANZONI"},
            {"SelectPlaylistSubtitle", "SELEZIONA PLAYLIST"},
            {"SongDetailsSubtitle"," DETTAGLI  CANZONE"},
            {"SongHasBeenAddedToPlaylist"," La canzone \"%s\" e' stata aggiunta alla playlist!"},
            {"SongSelection"," Inserisci un "+TextUtils.YELLOW+"numero"+TextUtils.RESET+" per selezionare la canzone, '"+TextUtils.GREEN+"next"+TextUtils.RESET+"' o '"+TextUtils.CYAN+"previous"+TextUtils.RESET+"' per navigare tra le \n pagine dei risultati oppure '"+TextUtils.RED+"cancel"+TextUtils.RESET+"' per tornare indietro."},
            {"SongSelectionEcho"," E' stata scelta la canzone:"},
            {"SongSelectionFromPlaylist"," Inserisci un "+TextUtils.YELLOW+"numero"+TextUtils.RESET+" per visualizzare le emozioni provate per una canzone, '"+TextUtils.GREEN+"next"+TextUtils.RESET+"' o '"+TextUtils.CYAN+"previous"+TextUtils.RESET+"' per\n navigare tra le pagine dei risultati oppure '"+TextUtils.YELLOW+"complete"+TextUtils.RESET+"' per completare il procedimento."},
            {"SongSelectionFromPlaylistFeedback"," Inserisci un "+TextUtils.YELLOW+"numero"+TextUtils.RESET+" per inserire le emozioni provate per una canzone, '"+TextUtils.GREEN+"next"+TextUtils.RESET+"' o '"+TextUtils.CYAN+"previous"+TextUtils.RESET+"' per\nnavigare tra le pagine dei risultati oppure '"+TextUtils.YELLOW+"complete"+TextUtils.RESET+"' per completare il procedimento."},
            {"SongsInPlaylist", " Canzoni attulamente all'interno della playlist:\n\n"},
            {"SupportedLanguagesOptions"," Linguaggi supportati:\n\n %1$s["+TextUtils.BLUE+"1"+TextUtils.RESET + "] Italiano\n %1$s["+TextUtils.BLUE+"2"+TextUtils.RESET + "] English\n\n Inserisci un "+TextUtils.YELLOW +"numero"+TextUtils.RESET +" per selezionare il linguaggio desiderato."},
            {"UserLoginSubtitle"," USER LOGIN"},
            {"Username"," Nome Utente:"},
            {"UserLogout"," E' stato effettuato il logout!"},
            {"VerifyANSISupport", " Il logo posto qui sopra appare privo di colori e include caratteri incomprensibili? s/n\n Scelta: "},
            {"ViewPlaylist","Consulta Playlist"},
            {"ViewPlaylistSubtitle"," CONSULTA PLAYLIST"},
            {"WARNING_FeedbackWillBeOverriden", " ["+TextUtils.YELLOW+"ATTENZIONE"+TextUtils.RESET+"] Hai gia' fornito un feedback per questa canzone, effettuando il salvataggio il tuo precedente feedback verra' sovrascritto. Desideri proseguire? s/n"},
            {"WARNING_CommentExceedsCharacterLimit", " [" + TextUtils.YELLOW + "ATTENZIONE" + TextUtils.RESET + "] Il commento inserito eccede il limite di 256 caratteri ed apparira' in questo modo:"},
            {"WelcomeUserOnLogin",TextUtils.GREEN + "\n Login effettuato, bentornato/a %s!\n " + TextUtils.RESET}

       };

    }

}
